namespace Hermes.SituationRoom.Shared.EnumClasses;

public enum Tag
{
    HUMAN_RIGHTS,
    ENVIRONMENT,
    CORRUPTION,
    ELECTIONS,
    CONFLICT,
    FREEDOM_OF_SPEECH,
    MIGRATION,
    POLICE_VIOLENCE,
    CORPORATE_ACCOUNTABILITY,
    SOCIAL_JUSTICE,
    HEALTHCARE,
    EDUCATION,
    LGBTQ_RIGHTS,
    GENDER_EQUALITY,
    TECHNOLOGY_PRIVACY,
    TRANSPARENCY,
}
